### PR TITLE
Support code gen for non-cuda targets with gpt-fast

### PR DESCRIPTION
**Pull request by mikekgfb**
Extend existing device variable to support code gen for other targets.

New args to generate
-- use_sdpa # by default, SDPA is disabled for best performance on CUDA. CPU presents different tradeoffs
--device ['cpu', 'cuda'] # we have the option to add devices such as MPS in the future

### CODE REVIEW

**Comment by jgong5** [comment]
cc @mingfeima

**Comment by mingfeima** [comment]
@mikekgfb cool !  We are just about to do something similar on the CPU device. We will add native support for int4 kernels on CPU:

* [_convert_weight_to_int4pack_cuda](https://github.com/pytorch/pytorch/blob/fcf6a76108be8e7b6db528b631a7b8ebdc7470ac/aten/src/ATen/native/native_functions.yaml#L4059)
* [_weight_int4pack_mm_cuda](https://github.com/pytorch/pytorch/blob/fcf6a76108be8e7b6db528b631a7b8ebdc7470ac/aten/src/ATen/native/native_functions.yaml#L4065)

So that int4 quant will run smoothly on CPU device, other dtypes bf16, f16 may just reply on MKL.

**Review by Chillee — COMMENTED** [review]
can we remove the `use_sdpa` flag here? I think it's not super needed for the results.

**Comment by mikekgfb** [comment]
I’ll remove it until we find whether it buys us performance (I’ve seen above additional improvements for cpu sdpa land from the Intel team land since I did my experiments)

We’ll also want to check out what code is generated for Int8 data type the performance drop is beyond what appears rational (5-6 QPS vs 2-ish QPS with int8)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgong5** [comment]
hi @mikekgfb May I know you plan of landing this PR? We want to propose a follow-up PR for Intel GPU based on it. Thanks!

**Comment by mikekgfb** [comment]
Waiting on a review which is required to merge. Addressed @Chillee 's feedback. If he's not available who else can review? @cpuhrsch @jisaacso ?

**Review by cpuhrsch — APPROVED** [review]

**Comment by mingfeima** [comment]
Cool this is merged :) I will wrap up code and upstream CPU backend optimization kernels to pytorch soon.

**Pull request merged**
